# Generated by Django 3.2.20 on 2023-07-24 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='diaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('learningOutcome', models.TextField(blank=True, null=True)),
                ('activityType', models.TextField(blank=True, null=True)),
                ('timeSpent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cpdCredits', models.DecimalField(decimal_places=2, max_digits=2)),
                ('practiceImpact', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
