# Generated by Django 3.2.20 on 2023-08-20 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpddiary', '0003_auto_20230730_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diary_entry',
            new_name='Entry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['date'], 'verbose_name_plural': 'Entries'},
        ),
    ]
