# Generated by Django 3.2.20 on 2023-08-29 21:19

import cpddiary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpddiary', '0004_auto_20230820_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cpdCredits',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[cpddiary.models.validate_positive_decimal]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='timeSpent',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[cpddiary.models.validate_positive_decimal]),
        ),
    ]
