# Generated by Django 3.2.20 on 2023-09-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpddiary', '0005_auto_20230829_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='activityType',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='learningOutcome',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='practiceImpact',
            field=models.TextField(null=True),
        ),
    ]
