# Generated by Django 3.2.20 on 2023-09-02 15:48

import cpddiary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpddiary', '0006_auto_20230902_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='activityType',
            field=models.TextField(null=True, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='cpdCredits',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[cpddiary.models.validate_positive_decimal], verbose_name='Cpd Credits Claimed'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='learningOutcome',
            field=models.TextField(null=True, verbose_name='Learning Outcome'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='practiceImpact',
            field=models.TextField(null=True, verbose_name='Practice Impact'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='timeSpent',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[cpddiary.models.validate_positive_decimal], verbose_name='Time Spent'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
