# Generated by Django 3.2.20 on 2023-09-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpddiary', '0007_auto_20230902_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timeSpent',
            field=models.CharField(max_length=20, null=True, verbose_name='Time Spent'),
        ),
    ]
