# Generated by Django 3.2.20 on 2023-09-02 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpddiary', '0008_alter_entry_timespent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cpdCredits',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cpd Credits Claimed'),
        ),
    ]
